export TF_LOG=ERROR

init:
	terraform init

import:
	terraform import nsxt_policy_tier0_gateway.t0_gateway "T0 Default"
	# terraform import nsxt_policy_tier0_gateway.t1_gateway "t1default"
	# seg test, vlan-segment
	# dhcp Default dhcp
	# IP pool VTEP-IP-Pool
